ALTER TABLE `utilisateur` 
ADD COLUMN `PRENOM` varchar(100) DEFAULT NULL AFTER `NOM`,
ADD COLUMN `GENRE` varchar(10) DEFAULT 'homme',
ADD COLUMN `AGE` int(11) DEFAULT NULL,
ADD COLUMN `TAILLE` int(11) DEFAULT NULL COMMENT 'Taille en cm',
ADD COLUMN `POIDS` int(11) DEFAULT NULL COMMENT 'Poids en kg',
ADD COLUMN `NIVEAU_CUISINE` varchar(20) DEFAULT 'debutant',
ADD COLUMN `RESTRICTIONS_ALIMENTAIRES` varchar(50) DEFAULT 'standard',
ADD COLUMN `PROFIL_COMPLETE` tinyint(1) DEFAULT 0;
